# Generated by Django 3.2.15 on 2023-02-12 18:10

import django.core.validators
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230211_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
