# Generated by Django 3.2.15 on 2023-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230212_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count2',
            field=models.IntegerField(default=0, verbose_name='Количество2'),
            preserve_default=False,
        ),
    ]
