# Generated by Django 3.2.15 on 2023-02-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230212_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='count2',
        ),
    ]
