# Generated by Django 3.2.15 on 2023-03-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230212_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Gather', 'В сборке'), ('Courier', 'У курьера'), ('Done', 'Выполнен')], db_index=True, default='New', max_length=10, verbose_name='Статус'),
        ),
    ]
