# Generated by Django 3.2.15 on 2023-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230301_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличными'), ('CARD', 'Картой')], db_index=True, max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
