# Generated by Django 3.2.15 on 2023-03-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called_date',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered_date',
            new_name='delivered_at',
        ),
    ]
